
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8001:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../logs/nginx:/var/log/nginx
      - ../../laravel:/var/www/laravel
    depends_on:
      - php

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../../laravel:/var/www/laravel
      - ../../src:/var/www/laravel
      - ../../logs/php:/var/log/php
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ../../logs/mysql:/var/log/mysql

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data_prod:
